### ISSUE TITLE
Make some validation functions static in validation.cpp

### ISSUE THREAD

**Issue by jnewbery** [jnewbery/bitcoin#12]
eg `ReadRawBlockFromDisk()`:

https://github.com/bitcoin/bitcoin/blob/cd6cb9745e13a62e130b11f78a13bcc1d424b05e/src/validation.cpp#L1177

eg `GetWitnessCommitmentIndex()` (which was made public in https://github.com/bitcoin/bitcoin/pull/16956)

**Comment by maflcko** [comment]
Why? Sounds like needless code churn for no reason.

**Comment by jnewbery** [comment]
Because the interface in header file should be kept the minimum size possible, and implementation hidden in the cpp file.

**Comment by maflcko** [comment]
Sure, to the extent where it makes sense. But at the same time it make testing hard and provokes the same discussions over and over again:

How do I tests this method?
* Do I put the function def in the header and remove the static? Preferable, imo.
* Do I put the function def in the unit test file and remove the static? Ugly, because the function def goes out of sync or must be updated twice
* Include the whole cpp file in the unit test to keep the static? Ouch
